"""Build the public field guide from an explicit source allowlist."""

from pathlib import Path
import hashlib
import importlib.util
import json
import re
import shutil
import subprocess
import sys


ROOT = Path(__file__).resolve().parent.parent
SITE_SOURCE = ROOT / "site-src"
OUTPUT = ROOT / "dist"
MARKER = ".generated-site"
GUIDE_MODULE_SPEC = importlib.util.spec_from_file_location("guide_pages", SITE_SOURCE / "guide_pages.py")
GUIDE_MODULE = importlib.util.module_from_spec(GUIDE_MODULE_SPEC)
GUIDE_MODULE_SPEC.loader.exec_module(GUIDE_MODULE)
GUIDES = GUIDE_MODULE.GUIDES
SKILL_MODULE_SPEC = importlib.util.spec_from_file_location("skill_catalog", SITE_SOURCE / "skill_catalog.py")
SKILL_MODULE = importlib.util.module_from_spec(SKILL_MODULE_SPEC)
SKILL_MODULE_SPEC.loader.exec_module(SKILL_MODULE)
FLOW_MODULE_SPEC = importlib.util.spec_from_file_location("flow_pages", SITE_SOURCE / "flow_pages.py")
FLOW_MODULE = importlib.util.module_from_spec(FLOW_MODULE_SPEC)
FLOW_MODULE_SPEC.loader.exec_module(FLOW_MODULE)
SEARCH_MODULE_SPEC = importlib.util.spec_from_file_location("search_index", SITE_SOURCE / "search_index.py")
SEARCH_MODULE = importlib.util.module_from_spec(SEARCH_MODULE_SPEC)
SEARCH_MODULE_SPEC.loader.exec_module(SEARCH_MODULE)


def asset_version(name: str) -> str:
    return hashlib.sha256((SITE_SOURCE / name).read_bytes()).hexdigest()[:8]

PAGES = (
    ("ui", ROOT / "网页UI元素速查.html", "UI 元素", "70 个可交互网页 UI 元素示例。看形态与状态，复制清楚的组件实现需求。", 'class="cmp"', 70),
    ("motion", ROOT / "动效速查.html", "动效", "79 种可交互动效，附实现规范分区。看触发和变化，复制清楚的动效实现需求。", 'class="effect-card"', 79),
)


def site_navigation(section: str) -> str:
    links = (("全部速查", "../", "home"), ("UI 元素", "../ui/", "ui"), ("动效", "../motion/", "motion")) + tuple(
        (guide["name"], f"../{slug}/", slug) for slug, guide in GUIDES.items()
    ) + (("UI 与交互 Skills", "../skills/", "skills"),)
    parts = []
    for label, href, key in links:
        current = ' aria-current="page"' if key == section else ""
        parts.append(f'<a href="{href}"{current}>{label}</a>')
    items = "".join(parts)
    more = f'<details class="site-more"><summary>分类目录</summary><div class="site-more-menu">{items}</div></details>'
    skip_target = "skills-main" if section == "skills" else "flows-main" if section == "flows" else "guide-main" if section in GUIDES else "site-content"
    return (
        f'<a class="site-skip" href="#{skip_target}">跳到主要内容</a>'
        '<nav class="site-nav" aria-label="网站导航"><div class="site-nav-inner">'
        '<a class="site-brand" href="../" aria-label="vibocoding助手全部速查">'
        '<span class="site-brand-icon" aria-hidden="true"><i></i><i></i><i></i></span>'
        '<span>vibocoding助手<small>INTERFACE FIELD GUIDE</small></span></a>'
        f'<div class="site-nav-links"><span class="site-nav-section">浏览目录</span>{items}{more}</div></div></nav>'
    )


def wrap_reference(source: str, section: str, description: str, card_class: str, expected_cards: int) -> str:
    if source.count(card_class) != expected_cards:
        raise ValueError(f"{section}: expected {expected_cards} cards, found {source.count(card_class)}")
    if source.count("<body>") != 1 or source.count('<main class="wrap">') != 1:
        raise ValueError(f"{section}: source page structure changed")

    head = (
        f'<meta name="description" content="{description}">\n'
        '<meta name="theme-color" content="#f7f7fd">\n'
        '<link rel="icon" href="../assets/favicon.svg" type="image/svg+xml">\n'
        f'<link rel="stylesheet" href="../assets/site.css?v={asset_version("site.css")}">\n'
        f'<link rel="stylesheet" href="../assets/theme.css?v={asset_version("theme.css")}">\n'
    )
    page = source.replace("</head>", head + "</head>", 1)
    page_title = "UI 元素速查" if section == "ui" else "动效速查"
    page, title_count = re.subn(r"<title>[^<]*</title>", f"<title>{page_title} · vibocoding助手</title>", page, count=1)
    if title_count != 1:
        raise ValueError(f"{section}: expected one page title")
    page = page.replace("<body>", f'<body class="site-reference" data-section="{section}">' + site_navigation(section) + '<div class="site-reference-workspace">', 1)
    page = page.replace('<main class="wrap">', '<main class="wrap" id="site-content">', 1)
    page = page.replace("</body>", f'</div>\n<script defer src="../assets/site.js?v={asset_version("site.js")}"></script>\n</body>', 1)
    return page


def prepare_output() -> None:
    if OUTPUT.exists():
        if not (OUTPUT / MARKER).is_file():
            raise RuntimeError(f"Refusing to replace non-generated directory: {OUTPUT}")
        shutil.rmtree(OUTPUT)
    OUTPUT.mkdir()
    (OUTPUT / MARKER).write_text("Generated by scripts/build_site.py\n", encoding="utf-8")


def build() -> None:
    subprocess.run([sys.executable, str(ROOT / "动效速查-src" / "build_motion_glossary.py")], check=True, cwd=ROOT)
    prepare_output()
    home = (SITE_SOURCE / "index.html").read_text(encoding="utf-8")
    search_entries = SEARCH_MODULE.build_search_index(
        (ROOT / "网页UI元素速查.html").read_text(encoding="utf-8"),
        (ROOT / "动效速查.html").read_text(encoding="utf-8"),
        GUIDES, GUIDE_MODULE, SKILL_MODULE.all_skills(),
    )
    search_json = json.dumps(search_entries, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    home = home.replace("__SEARCH_INDEX__", search_json, 1)
    for name in ("site.css", "theme.css", "home.css", "home.js"):
        home = home.replace(f'./assets/{name}"', f'./assets/{name}?v={asset_version(name)}"')
    (OUTPUT / "index.html").write_text(home, encoding="utf-8")
    assets = OUTPUT / "assets"
    assets.mkdir()
    for name in ("site.css", "theme.css", "site.js", "home.css", "home.js", "guides.css", "guides.js", "visual-styles.css", "skills.css", "skills.js", "flows.css", "flows.js", "favicon.svg"):
        shutil.copy2(SITE_SOURCE / name, assets / name)
    for section, path, label, description, card_class, expected_cards in PAGES:
        destination = OUTPUT / section
        destination.mkdir()
        html = wrap_reference(path.read_text(encoding="utf-8"), section, description, card_class, expected_cards)
        (destination / "index.html").write_text(html, encoding="utf-8")
        if section == "motion":
            for name in ("motion-demo-gallery.html", "motion-demo-detail.html"):
                shutil.copy2(ROOT / name, destination / name)
        print(f"Built {label}: {destination / 'index.html'}")
    for slug, guide in GUIDES.items():
        destination = OUTPUT / slug
        destination.mkdir()
        html = GUIDE_MODULE.render_guide_page(slug, site_navigation(slug), asset_version("site.css"), asset_version("guides.css"), asset_version("visual-styles.css"), asset_version("theme.css"), asset_version("guides.js"))
        (destination / "index.html").write_text(html, encoding="utf-8")
        print(f"Built {guide['name']}: {destination / 'index.html'}")
    skill_destination = OUTPUT / "skills"
    skill_destination.mkdir()
    skill_html = SKILL_MODULE.render_page(site_navigation("skills"), asset_version("site.css"), asset_version("skills.css"), asset_version("theme.css"), asset_version("skills.js"))
    (skill_destination / "index.html").write_text(skill_html, encoding="utf-8")
    print(f"Built UI 与交互 Skills: {skill_destination / 'index.html'}")
    flow_destination = OUTPUT / "flows"
    flow_destination.mkdir()
    flow_html = FLOW_MODULE.render_page(site_navigation("flows"), asset_version("site.css"), asset_version("guides.css"), asset_version("flows.css"), asset_version("theme.css"), asset_version("flows.js"))
    (flow_destination / "index.html").write_text(flow_html, encoding="utf-8")
    print(f"Built 组合流程: {flow_destination / 'index.html'}")
    files = sorted(str(path.relative_to(OUTPUT)) for path in OUTPUT.rglob("*") if path.is_file())
    expected = sorted((MARKER, "index.html", "ui/index.html", "motion/index.html", "motion/motion-demo-gallery.html", "motion/motion-demo-detail.html", "assets/site.css", "assets/theme.css", "assets/site.js", "assets/home.css", "assets/home.js", "assets/guides.css", "assets/guides.js", "assets/visual-styles.css", "assets/skills.css", "assets/skills.js", "assets/flows.css", "assets/flows.js", "assets/favicon.svg", "skills/index.html", "flows/index.html", *(f"{slug}/index.html" for slug in GUIDES)))
    if files != expected:
        raise RuntimeError(f"Unexpected build files: {files}")
    print("Built site: 10 pages, 189 entries + 动效实现规范, curated static output")


if __name__ == "__main__":
    build()
